apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-broker-config
  namespace: default
data:
  RABBITMQ_PORT: "5672"
  RABBITMQ_PROTOCOL: amqp
  RABBITMQ_QUEUE: temperature
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-broker
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: broker
  ports:
    - name: data
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: management
      protocol: TCP
      port: 15672
      targetPort: 15672
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-broker
  namespace: default
  labels: 
    app: broker
spec:
  selector:
    matchLabels:
      app: broker
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0 
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
      - name: rabbitmq-broker
        image: nathapaulino/broker
        ports:
        - containerPort: 5672
        - containerPort: 15672
        envFrom:
        - configMapRef:
            name: rabbitmq-broker-config
        - secretRef:
            name: rabbitmq-broker-secrets
---